In [1]:
##import all the required libries
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pickle

In [2]:
df = pd.read_csv("Churn_Modelling.csv")

In [3]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
##preprocess the data 
## Drop irrelevant COlumns

df = df.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [5]:
df.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder
columns = ['Gender']
for col in columns:
   le = LabelEncoder()
   df[col] = le.fit_transform(df[col])

In [16]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# 1. Encoder create
Oh = OneHotEncoder(sparse_output=False)

# 2. Encode Geography
encoded = Oh.fit_transform(df[['Geography']])

# 3. Check shape
print("Encoded shape:", encoded.shape)
print("Columns:", Oh.get_feature_names_out(['Geography']))

# 4. Convert to DataFrame
encoded_df = pd.DataFrame(
    encoded,
    columns=Oh.get_feature_names_out(['Geography']),
    index=df.index
)

encoded_df.head()

Encoded shape: (10000, 3)
Columns: ['Geography_France' 'Geography_Germany' 'Geography_Spain']

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [21]:
data = pd.concat(
    [df.drop('Geography', axis=1), encoded_df],
    axis=1
)

In [22]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [25]:
## save the encoder and scaler

import pickle

with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(le, file)

with open('onehot_encoder.pkl', 'wb') as file:
    pickle.dump(Oh, file)

In [27]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [ ]:
#devide the dataset into target value and independented feature
from sklearn.model_selection import train_test_split

In [31]:
X=data.drop(["Exited"],axis=1)
y=data["Exited"]

In [33]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [34]:
##lets do standard dacler
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [35]:
with open('sc.pkl','wb') as file:
    pickle.dump(sc,file)

ANN IMPLEMANTION

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime