In [4]:
##import all the lib
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

d:\ml project\venv\lib\site-packages\requests\__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

In [5]:
##load the trained model, scaler pickle,onehot
model = load_model('model.h5')

##load the encoder and scaler
with open('label_encoder.pkl','rb') as file:
    label_encoder = pickle.load(file)

with open('onehot_encoder.pkl','rb') as file:
    onehot_encoder=pickle.load(file)

with open('sc.pkl','rb') as file:
    sc=pickle.load(file)

In [6]:
##example input data 
input_data={
    'CreditScore':600,
    "Geography":'France',
    "Gender":"Male",
    "Age":40,
    "Tenure":3,
    "Balance":60000,
    "NumOfProducts":2,
    "HasCrCard":1,
    "IsActiveMember":1,
    "EstimatedSalary":50000 
}

In [13]:
geo_encoded = onehot_encoder.transform([[input_data["Geography"]]])

geo_encoded = pd.DataFrame(
    geo_encoded,
    columns=onehot_encoder.get_feature_names_out(['Geography'])
)
geo_encoded

d:\ml project\venv\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [14]:
##conver input data into DAtaFRame 
input_df= pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [18]:
##encode categorical variable
input_df['Gender']=label_encoder.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [19]:
##concatination with one hot encoded 
input_df = pd.concat([input_df.drop('Geography',axis=1)],geo_encoded,axis=1)
input_df

TypeError: concat() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given